import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import FloatingHearts from "@/animationComp/FloatingHearts";
import Footer from "@/comp/Footer";
import StickeyCornerGif from "@/comp/gif/StickeyCornerGif";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-screen antialiased bg-black`}
      >
        <div className="fixed inset-0 pointer-events-none z-40">
          <FloatingHearts />
        </div>
        {children}
        {/* Single Sticky GIF in Right Corner - appears on all pages */}
        <StickeyCornerGif />
        <Footer />
      </body>
    </html>
  );
}
